# Generated by Django 4.1.5 on 2023-03-04 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_text_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='text_post',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
