# Generated by Django 4.1.5 on 2023-01-18 16:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_event_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='priority',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('Medium', 'Medium'), ('Low', 'Low')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
