# Generated by Django 4.1.5 on 2023-01-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
