# Generated by Django 3.2.14 on 2022-08-10 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_subject', models.CharField(choices=[('Eco', 'Economics'), ('Art', 'Art'), ('Eng', 'English'), ('Mat', 'Maths'), ('Bio', 'Biology'), ('Phy', 'Physics'), ('Che', 'Chemistry'), ('Com', 'Computer Science'), ('Pol', 'Politics'), ('His', 'History'), ('Geo', 'Geography'), ('Psy', 'Psychology'), ('Fur', 'Further Maths'), ('Spa', 'Spanish'), ('PE', 'Physical Education')], max_length=20)),
                ('test_title', models.CharField(max_length=100)),
                ('date', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31')], max_length=4)),
                ('month', models.CharField(choices=[('Jan', '1'), ('Feb', '2'), ('Mar', '3'), ('Apr', '4'), ('May', '5'), ('Jun', '6'), ('Jul', '7'), ('Aug', '8'), ('Sep', '9'), ('Oct', '10'), ('Nov', '11'), ('Dec', '12')], max_length=4)),
                ('year', models.CharField(choices=[('2021', '2021'), ('2022', '2022'), ('2023', '2023')], max_length=4)),
                ('test_marks', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('test_outof', models.DecimalField(decimal_places=0, default=0, max_digits=4)),
                ('submitted', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
