# Generated by Django 4.1.5 on 2023-01-12 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_remove_tests_date_remove_tests_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(choices=[('Economics', 'Economics'), ('Art', 'Art'), ('English', 'English'), ('Maths', 'Maths'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry'), ('Computer Science', 'Computer Science'), ('Politics', 'Politics'), ('History', 'History'), ('Geography', 'Geography'), ('Psychology', 'Psychology'), ('Further Maths', 'Further Maths'), ('Spanish', 'Spanish'), ('Physical Education', 'Physical Education')], max_length=20, unique=True)),
            ],
        ),
    ]
