# Generated by Django 4.1.5 on 2023-01-12 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_subjects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.subjects'),
        ),
    ]
