# Generated by Django 4.1.5 on 2023-01-12 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topics',
            old_name='resources',
            new_name='resource_url',
        ),
        migrations.AddField(
            model_name='topics',
            name='resource_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
