# Generated by Django 3.2.14 on 2022-08-10 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_resource', models.CharField(choices=[('Eco', 'Economics'), ('Art', 'Art'), ('Eng', 'English'), ('Mat', 'Maths'), ('Bio', 'Biology'), ('Phy', 'Physics'), ('Che', 'Chemistry'), ('Com', 'Computer Science'), ('Pol', 'Politics'), ('His', 'History'), ('Geo', 'Geography'), ('Psy', 'Psychology'), ('Fur', 'Further Maths'), ('Spa', 'Spanish'), ('PE', 'Physical Education')], max_length=20)),
                ('chapter_no', models.DecimalField(decimal_places=0, default=0, max_digits=3)),
                ('chapter_title', models.CharField(max_length=100)),
                ('notes', models.URLField(blank=True)),
                ('flashcards', models.URLField(blank=True)),
                ('videos', models.URLField(blank=True)),
                ('submitted', models.DateField(auto_now_add=True)),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
