# Generated by Django 3.2.14 on 2022-08-31 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.jpg', upload_to='profile_images')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('year_group', models.CharField(choices=[('12', 'Year 12'), ('13', 'Year 13')], max_length=10)),
                ('subject1', models.CharField(choices=[('Eco', 'Economics'), ('Art', 'Art'), ('Eng', 'English'), ('Mat', 'Maths'), ('Bio', 'Biology'), ('Phy', 'Physics'), ('Che', 'Chemistry'), ('Com', 'Computer Science'), ('Pol', 'Politics'), ('His', 'History'), ('Geo', 'Geography'), ('Psy', 'Psychology'), ('Fur', 'Further Maths'), ('Spa', 'Spanish'), ('PE', 'Physical Education')], max_length=20)),
                ('subject2', models.CharField(choices=[('Eco', 'Economics'), ('Art', 'Art'), ('Eng', 'English'), ('Mat', 'Maths'), ('Bio', 'Biology'), ('Phy', 'Physics'), ('Che', 'Chemistry'), ('Com', 'Computer Science'), ('Pol', 'Politics'), ('His', 'History'), ('Geo', 'Geography'), ('Psy', 'Psychology'), ('Fur', 'Further Maths'), ('Spa', 'Spanish'), ('PE', 'Physical Education')], max_length=20)),
                ('subject3', models.CharField(choices=[('Eco', 'Economics'), ('Art', 'Art'), ('Eng', 'English'), ('Mat', 'Maths'), ('Bio', 'Biology'), ('Phy', 'Physics'), ('Che', 'Chemistry'), ('Com', 'Computer Science'), ('Pol', 'Politics'), ('His', 'History'), ('Geo', 'Geography'), ('Psy', 'Psychology'), ('Fur', 'Further Maths'), ('Spa', 'Spanish'), ('PE', 'Physical Education')], max_length=20)),
                ('subject4', models.CharField(blank=True, choices=[('Eco', 'Economics'), ('Art', 'Art'), ('Eng', 'English'), ('Mat', 'Maths'), ('Bio', 'Biology'), ('Phy', 'Physics'), ('Che', 'Chemistry'), ('Com', 'Computer Science'), ('Pol', 'Politics'), ('His', 'History'), ('Geo', 'Geography'), ('Psy', 'Psychology'), ('Fur', 'Further Maths'), ('Spa', 'Spanish'), ('PE', 'Physical Education')], max_length=20)),
                ('target1', models.CharField(choices=[('A*', 'A*'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('target2', models.CharField(choices=[('A*', 'A*'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('target3', models.CharField(choices=[('A*', 'A*'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('target4', models.CharField(blank=True, choices=[('A*', 'A*'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
