# Generated by Django 4.1.5 on 2023-01-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0002_profile2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
