# Generated by Django 4.1.5 on 2023-01-12 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_tests_test_subject'),
        ('user_profiles', '0003_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile2',
            name='subject1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='academic.subjects'),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='subject2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='academic.subjects'),
        ),
    ]
