# Generated by Django 4.1.5 on 2023-01-12 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_tests_test_subject'),
        ('user_profiles', '0004_alter_profile2_subject1_alter_profile2_subject2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile2',
            name='subject3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='academic.subjects'),
        ),
        migrations.AlterField(
            model_name='profile2',
            name='subject4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='academic.subjects'),
        ),
    ]
